### ISSUE TITLE
pashutk.ru/ergopad/ is 404 error

### ISSUE THREAD

**Issue by tamago324** [pashutk/ergopad#4]
Accessing pashutk.ru/ergopad/  results in a 404 error.
Sorry if I am mistaken.

**Comment by pashutk** [comment]
Hi @tamago324!

No, you're absolutely right, I've migrated to an international domain and forgot to set up all the redirects. Now it should work, could you please check that the same address is redirecting you to the working page?

**Comment by tamago324** [comment]
We're connected!
Thank you for fixing it!
